/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.uk.co.caprica.vlcj)
    api(libs.org.bytedeco.javacv)
    api(libs.org.bytedeco.ffmpeg)
    api(libs.framework.frameworkautomation)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
}

group = "Selenovid"
version = "0.0.1-SNAPSHOT"
description = "Selenovid"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
